// Code generated by MockGen. DO NOT EDIT.
// Source: clash.go
//
// Generated by this command:
//
//	mockgen -source=clash.go -destination=../mocks/clash_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClashClient is a mock of ClashClient interface.
type MockClashClient struct {
	ctrl     *gomock.Controller
	recorder *MockClashClientMockRecorder
	isgomock struct{}
}

// MockClashClientMockRecorder is the mock recorder for MockClashClient.
type MockClashClientMockRecorder struct {
	mock *MockClashClient
}

// NewMockClashClient creates a new mock instance.
func NewMockClashClient(ctrl *gomock.Controller) *MockClashClient {
	mock := &MockClashClient{ctrl: ctrl}
	mock.recorder = &MockClashClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClashClient) EXPECT() *MockClashClientMockRecorder {
	return m.recorder
}

// GetPlayer mocks base method.
func (m *MockClashClient) GetPlayer(ctx context.Context, tag string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", ctx, tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockClashClientMockRecorder) GetPlayer(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockClashClient)(nil).GetPlayer), ctx, tag)
}

// GetPlayerBattleLog mocks base method.
func (m *MockClashClient) GetPlayerBattleLog(ctx context.Context, tag string, limit int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerBattleLog", ctx, tag, limit)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerBattleLog indicates an expected call of GetPlayerBattleLog.
func (mr *MockClashClientMockRecorder) GetPlayerBattleLog(ctx, tag, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerBattleLog", reflect.TypeOf((*MockClashClient)(nil).GetPlayerBattleLog), ctx, tag, limit)
}

// GetPlayersUpcomingChests mocks base method.
func (m *MockClashClient) GetPlayersUpcomingChests(ctx context.Context, tag string, limit int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayersUpcomingChests", ctx, tag, limit)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayersUpcomingChests indicates an expected call of GetPlayersUpcomingChests.
func (mr *MockClashClientMockRecorder) GetPlayersUpcomingChests(ctx, tag, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayersUpcomingChests", reflect.TypeOf((*MockClashClient)(nil).GetPlayersUpcomingChests), ctx, tag, limit)
}
