// Code generated by MockGen. DO NOT EDIT.
// Source: clash.go
//
// Generated by this command:
//
//	mockgen -source=clash.go -destination=../mocks/clash_api.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClashAPI is a mock of ClashAPI interface.
type MockClashAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClashAPIMockRecorder
	isgomock struct{}
}

// MockClashAPIMockRecorder is the mock recorder for MockClashAPI.
type MockClashAPIMockRecorder struct {
	mock *MockClashAPI
}

// NewMockClashAPI creates a new mock instance.
func NewMockClashAPI(ctrl *gomock.Controller) *MockClashAPI {
	mock := &MockClashAPI{ctrl: ctrl}
	mock.recorder = &MockClashAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClashAPI) EXPECT() *MockClashAPIMockRecorder {
	return m.recorder
}

// GetCards mocks base method.
func (m *MockClashAPI) GetCards(ctx context.Context) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCards", ctx)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCards indicates an expected call of GetCards.
func (mr *MockClashAPIMockRecorder) GetCards(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCards", reflect.TypeOf((*MockClashAPI)(nil).GetCards), ctx)
}

// GetPlayer mocks base method.
func (m *MockClashAPI) GetPlayer(ctx context.Context, tag string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", ctx, tag)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockClashAPIMockRecorder) GetPlayer(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockClashAPI)(nil).GetPlayer), ctx, tag)
}

// GetPlayerBattleLog mocks base method.
func (m *MockClashAPI) GetPlayerBattleLog(ctx context.Context, tag string, limit int) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerBattleLog", ctx, tag, limit)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerBattleLog indicates an expected call of GetPlayerBattleLog.
func (mr *MockClashAPIMockRecorder) GetPlayerBattleLog(ctx, tag, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerBattleLog", reflect.TypeOf((*MockClashAPI)(nil).GetPlayerBattleLog), ctx, tag, limit)
}
