// Code generated by MockGen. DO NOT EDIT.
// Source: llm.go
//
// Generated by this command:
//
//	mockgen -source=llm.go -destination=../../internal/mocks/llm.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLLM is a mock of LLM interface.
type MockLLM struct {
	ctrl     *gomock.Controller
	recorder *MockLLMMockRecorder
	isgomock struct{}
}

// MockLLMMockRecorder is the mock recorder for MockLLM.
type MockLLMMockRecorder struct {
	mock *MockLLM
}

// NewMockLLM creates a new mock instance.
func NewMockLLM(ctrl *gomock.Controller) *MockLLM {
	mock := &MockLLM{ctrl: ctrl}
	mock.recorder = &MockLLMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLM) EXPECT() *MockLLMMockRecorder {
	return m.recorder
}

// generateReply mocks base method.
func (m *MockLLM) generateReply(ctx context.Context, prompt string, gameTag *string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "generateReply", ctx, prompt, gameTag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// generateReply indicates an expected call of generateReply.
func (mr *MockLLMMockRecorder) generateReply(ctx, prompt, gameTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "generateReply", reflect.TypeOf((*MockLLM)(nil).generateReply), ctx, prompt, gameTag)
}
