// Code generated by MockGen. DO NOT EDIT.
// Source: s3.go
//
// Generated by this command:
//
//	mockgen -source=s3.go -destination=../mocks/s3.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3ObjectStorage is a mock of S3ObjectStorage interface.
type MockS3ObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockS3ObjectStorageMockRecorder
	isgomock struct{}
}

// MockS3ObjectStorageMockRecorder is the mock recorder for MockS3ObjectStorage.
type MockS3ObjectStorageMockRecorder struct {
	mock *MockS3ObjectStorage
}

// NewMockS3ObjectStorage creates a new mock instance.
func NewMockS3ObjectStorage(ctrl *gomock.Controller) *MockS3ObjectStorage {
	mock := &MockS3ObjectStorage{ctrl: ctrl}
	mock.recorder = &MockS3ObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ObjectStorage) EXPECT() *MockS3ObjectStorageMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockS3ObjectStorage) DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObject", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3ObjectStorageMockRecorder) DeleteObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockS3ObjectStorage)(nil).DeleteObject), varargs...)
}

// PutObject mocks base method.
func (m *MockS3ObjectStorage) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3ObjectStorageMockRecorder) PutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3ObjectStorage)(nil).PutObject), varargs...)
}
